#!/bin/bash
basepath=$(cd `dirname $0`; pwd)

cd $basepath || exit 1
if [[ "`git --no-pager diff`" == "" ]];then
  echo 'no update'
else
  git add .
  git commit -m "auto saved"
  git push
  hexo d -g
fi
